-- MySQL Script generated by MySQL Workbench
-- Tue Aug 27 21:48:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema axey_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema axey_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `axey_db` DEFAULT CHARACTER SET utf8 ;
USE `axey_db` ;

-- -----------------------------------------------------
-- Table `axey_db`.`Avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Avaliacoes` (
  `idAvaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pontualidade` INT NOT NULL,
  `qualidade_servico` INT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  `create_avalicao` DATE NULL,
  `altera_avalicao` DATE NULL,
  PRIMARY KEY (`idAvaliacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Planos` (
  `idPlano` INT NOT NULL AUTO_INCREMENT,
  `preco_planos` DECIMAL(10,2) NOT NULL,
  `quantidade_fotos` VARCHAR(4) NULL,
  `quantidade_video` VARCHAR(4) NULL,
  `data_assinatura` DATE NULL,
  `data_altera_assinatura` DATE NULL,
  PRIMARY KEY (`idPlano`),
  UNIQUE INDEX `idPlano_UNIQUE` (`idPlano` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Prestadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Prestadores` (
  `idVendedor` INT NOT NULL AUTO_INCREMENT,
  `Avaliacoes_idAvaliacao` INT UNSIGNED NOT NULL,
  `Enderecos_idEndereco` INT NOT NULL,
  `Planos_idPlano` INT NOT NULL,
  `nome_resp_legal` VARCHAR(100) NOT NULL,
  `nome_fantasia` VARCHAR(100) NOT NULL,
  `razao_social` VARCHAR(255) NOT NULL,
  `cpnj` VARCHAR(15) NOT NULL,
  `descricao_negocio` LONGTEXT NOT NULL,
  `cpf_prestadores` VARCHAR(11) NOT NULL,
  `email_prestadores` VARCHAR(145) NOT NULL,
  `senha_prestadores` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `create_prestadores` DATE NULL,
  `altera_prestadores` DATE NULL,
  `data_inativacao` DATE NULL,
  PRIMARY KEY (`idVendedor`, `Avaliacoes_idAvaliacao`, `Enderecos_idEndereco`),
  UNIQUE INDEX `idVendedores_UNIQUE` (`idVendedor` ASC),
  INDEX `fk_Vendedores_Avaliacoes1_idx` (`Avaliacoes_idAvaliacao` ASC),
  INDEX `fk_Prestadores_Planos1_idx` (`Planos_idPlano` ASC),
  CONSTRAINT `fk_Vendedores_Avaliacoes1`
    FOREIGN KEY (`Avaliacoes_idAvaliacao`)
    REFERENCES `axey_db`.`Avaliacoes` (`idAvaliacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestadores_Planos1`
    FOREIGN KEY (`Planos_idPlano`)
    REFERENCES `axey_db`.`Planos` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Enderecos` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT(10) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  `cep` VARCHAR(8) NULL,
  `logradouro` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`idEndereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`idEndereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `create_clientes` DATE NULL,
  ` nome_cliente` VARCHAR(100) NOT NULL,
  `nome_social` VARCHAR(100) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(145) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `Enderecos_idEndereco` INT NOT NULL,
  `celular` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(14) NULL,
  `altera_clientes` DATE NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `idCompradores_UNIQUE` (`idCliente` ASC),
  INDEX `fk_Clientes_Enderecos1_idx` (`Enderecos_idEndereco` ASC),
  CONSTRAINT `fk_Clientes_Enderecos1`
    FOREIGN KEY (`Enderecos_idEndereco`)
    REFERENCES `axey_db`.`Enderecos` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `titulo_categoria` VARCHAR(100) NOT NULL,
  `descricao_categoria` LONGTEXT NOT NULL,
  `create_categoria` DATE NULL,
  `altera_categoria` DATE NULL,
  PRIMARY KEY (`idCategoria`),
  UNIQUE INDEX `idCategorias_UNIQUE` (`idCategoria` ASC),
  UNIQUE INDEX `nome_categoria_UNIQUE` (`titulo_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Produtos` (
  `idProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Vendedores_idVendedor` INT NOT NULL,
  `Categorias_idCategoria` INT NOT NULL,
  `nome_produto` VARCHAR(130) NOT NULL,
  `valor_produto` VARCHAR(9) NOT NULL,
  `descricao_produto` VARCHAR(255) NOT NULL,
  `imagem_produto` LONGTEXT NOT NULL,
  `video_produto` LONGTEXT NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  `alter_date` DATE NULL,
  `create_date` DATE NULL,
  PRIMARY KEY (`idProduto`, `Vendedores_idVendedor`, `Categorias_idCategoria`),
  INDEX `fk_Produtos_Vendedores_idx` (`Vendedores_idVendedor` ASC),
  INDEX `fk_Produtos_Categorias1_idx` (`Categorias_idCategoria` ASC),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC),
  CONSTRAINT `fk_Produtos_Vendedores`
    FOREIGN KEY (`Vendedores_idVendedor`)
    REFERENCES `axey_db`.`Prestadores` (`idVendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `axey_db`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Segmentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Segmentos` (
  `idSegmento` INT NOT NULL AUTO_INCREMENT,
  `nome_seguimento` VARCHAR(200) NOT NULL,
  `descricao_seguimento` LONGTEXT NULL,
  PRIMARY KEY (`idSegmento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `tipos_usuario` VARCHAR(1) NULL,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `imagem_adm` LONGTEXT NULL,
  `celular` VARCHAR(12) NOT NULL,
  `telefone` VARCHAR(12) NULL,
  `create_usuario` DATE NULL,
  `altera_usuario` DATE NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Contratacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Contratacoes` (
  `Produtos_idProduto` INT UNSIGNED NOT NULL,
  `Produtos_Vendedores_idVendedor` INT NOT NULL,
  `Produtos_Categorias_idCategoria` INT NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  `data_contrato` DATE NULL,
  PRIMARY KEY (`Produtos_idProduto`, `Produtos_Vendedores_idVendedor`, `Produtos_Categorias_idCategoria`, `Clientes_idCliente`),
  INDEX `fk_Produtos_has_Clientes_Clientes1_idx` (`Clientes_idCliente` ASC),
  INDEX `fk_Produtos_has_Clientes_Produtos1_idx` (`Produtos_idProduto` ASC, `Produtos_Vendedores_idVendedor` ASC, `Produtos_Categorias_idCategoria` ASC),
  CONSTRAINT `fk_Produtos_has_Clientes_Produtos1`
    FOREIGN KEY (`Produtos_idProduto` , `Produtos_Vendedores_idVendedor` , `Produtos_Categorias_idCategoria`)
    REFERENCES `axey_db`.`Produtos` (`idProduto` , `Vendedores_idVendedor` , `Categorias_idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Clientes_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `axey_db`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `axey_db`.`Agendamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `axey_db`.`Agendamentos` (
  `idAgendamento` INT NOT NULL AUTO_INCREMENT,
  `Clientes_idCliente` INT NOT NULL,
  `Prestadores_idVendedor` INT NOT NULL,
  `Prestadores_Avaliacoes_idAvaliacao` INT UNSIGNED NOT NULL,
  `Prestadores_Enderecos_idEndereco` INT NOT NULL,
  `dia_selecionado` DATE NOT NULL,
  `titulo_servico` VARCHAR(170) NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `create_agendamento` DATE NULL,
  `altera_agendamento` DATE NULL,
  PRIMARY KEY (`idAgendamento`, `Clientes_idCliente`, `Prestadores_idVendedor`, `Prestadores_Avaliacoes_idAvaliacao`, `Prestadores_Enderecos_idEndereco`),
  INDEX `fk_Agendamentos_Clientes1_idx` (`Clientes_idCliente` ASC),
  INDEX `fk_Agendamentos_Prestadores1_idx` (`Prestadores_idVendedor` ASC, `Prestadores_Avaliacoes_idAvaliacao` ASC, `Prestadores_Enderecos_idEndereco` ASC),
  CONSTRAINT `fk_Agendamentos_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `axey_db`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamentos_Prestadores1`
    FOREIGN KEY (`Prestadores_idVendedor` , `Prestadores_Avaliacoes_idAvaliacao` , `Prestadores_Enderecos_idEndereco`)
    REFERENCES `axey_db`.`Prestadores` (`idVendedor` , `Avaliacoes_idAvaliacao` , `Enderecos_idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
